### ISSUE TITLE
有个问题请教

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [wshuyi/demo-helloworld-streamlit#1]
@st.cache
def load_data():
    df = pd.read_csv("data.csv")
    df = df[['EVENT_TYPE', 'CREATE_TIME', 'COUNTY', 'LAT', 'LON']]
    df.columns = ['event_type', 'time', 'county', 'lat', 'lon']
    return df

这里，
    df = df[['EVENT_TYPE', 'CREATE_TIME', 'COUNTY', 'LAT', 'LON']]
    df.columns = ['event_type', 'time', 'county', 'lat', 'lon']

的用意是什么呢？

**Comment by wshuyi** [comment]
前一句，取需要的列。后一句，改名。因为绘图的时候，需要 lat, lon 这样的名称，来绘制地理位置。
